# Generated by Django 2.1.7 on 2020-03-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueboard', '0002_auto_20200323_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='issue',
        ),
    ]
