# Generated by Django 2.1.7 on 2020-03-24 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issueboard', '0003_auto_20200323_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, max_length=4000),
            preserve_default=False,
        ),
    ]
